### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by itz63c** [EssentialOpenSource/device_essential_mata#1]
Why is there no commit history

**Comment by joshuaherman** [comment]
Because it's a brand new repo. Please don't open issues that are not bugs or feature request. 

Let's keep this place clean.

**Comment by itz63c** [comment]
> Because it's a brand new repo. Please don't open issues that are not bugs or feature request.
> 
> Let's keep this place clean.

I too can kang wahoo and call it a new repo

**Comment by itz63c** [comment]
it's not a "new" repo, this was more than likely done intentionally.
for what reason? we don't quite know that much.

**Comment by TotalChris** [comment]
@itz63c Essential announced they would be going out of business, and that this code would be posted here a few days ago. Again, please keep the issues clean

**Comment by itz63c** [comment]
> @itz63c Essential announced they would be going out of business, and that this code would be posted here a few days ago. Again, please keep the issues clean

I know that, that isn't the point though, why did they remove their commit history? Or do you seriously think they didn't keep any?

**Comment by TotalChris** [comment]
Perhaps there's some proprietary parts they want to keep out. Who really knows what Essential is even thinking anymore bro.

**Comment by phly95** [comment]
To Essential: Thank you for this great phone. I am happy you made a single phone and truely made it the best it could be over the years. Also thank you for posting the source on Github, so others may continue the legacy of this ever-evolving phone.
Every time you made an update, I appreciated it. From the time you fixed Bluetooth absolute volume, to enhancing the brightness and volume control to allow for quieter and darker display at night. The essential notch settings in developer options was a godsend for reading apps as well as ultrawide video on platforms like Netflix. While I wished for a better internal speaker, and maybe a headphone jack, I guess that was just a product of its time.
The PH-1 is dead, Long live the PH-1 (on XDA developers)

PS: I plan to continue using this phone for quite a while into the foreseeable future. No reason to upgrade at this point.
