### ISSUE TITLE
Need ability to unbrick from QDL Mode

### ISSUE THREAD

**Issue by shahmirn** [EssentialOpenSource/device_essential_mata#11]
Hello,

Now that the company is no more and there is no method of sending in our phones, can you please provide a method to unbrick from QDL mode?

Firehose files would be great, but if that's not possible, then please provide some other method to unbrick from QDL.

**Comment by TotalChris** [comment]
ㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤ

**Comment by TotalChris** [comment]
Also I do believe they've previously stated that those files are property of Qualcomm, and releasing them could provoke legal action against the leaker and any former company members. As much as I would like to have them.

**Comment by itz63c** [comment]
OnePlus's get leaked time and time again, no legal issues have surfaced
yet. It's been years. I highly doubt a company as lowkey as Essential would
be targeted if it was anonymously published online somewhere.

**Comment by shahmirn** [comment]
If they can't provide the firehose files, they need to provide some alternate mechanism for people to be able to recover their phones.

Potentially an exe that can be ran, and it detects that phone is in QDL mode, and then flashes it automatically with the latest boot/vendor/system/etc images.
