### ISSUE TITLE
EDL firehose request

### ISSUE THREAD

**Issue by Darkhand81** [EssentialOpenSource/device_essential_mata#2]
Can the EDL firehose please be included? This is required to unbrick phones, and will be otherwise impossible to do without vendor support.

Thanks for all you guys did!

**Comment by TotalChris** [comment]
+1 on this issue. Would love to revive my dead PH-1 using the newly open-sourced tools.

**Comment by itz63c** [comment]
+10000

**Comment by D1ll4nT** [comment]
It would be appreciated by the people who truly loved their Essential phone and have held on to it in hopes you all would be kind enough to help us fix it one day. 

Please, please release the files so that I can bring my phone back to life. I really did enjoy using it.

**Comment by UrbanPotato** [comment]
yes +1

**Comment by D1ll4nT** [comment]
I just stumbled upon what I think is a fantastic suggestion from Throwaway_97534 on Reddit. Would this be a viable alternative to use instead of the edl programmers? 
![Screenshot_20200215-090645_Reddit](https://user-images.githubusercontent.com/36722397/74590324-0479b400-4fd3-11ea-9d34-437811243ecc.jpg)

**Comment by UrbanPotato** [comment]
completely unrelated to what we are talking about and not easy to implement also fastboot oem unlock exists 9008 is what you get when the bootloader is DEAD

**Comment by TotalChris** [comment]
Lmao I was the guy that said 'thats a cool idea'

Yeah basically a different thing

**Comment by Arunscape** [comment]
hi yes, +1 on this issue

It's unfortunate that many of us have expensive paperweights for a problem that could be trivially solved with software :/

**Comment by TotalChris** [comment]
Hello, everyone. I just received an email from Essential support, stating that we will not see Firehose files. Here is a screenshot:

![image](https://user-images.githubusercontent.com/41809916/74777421-7407d180-5267-11ea-8c5d-80f65236f610.png)

I replied asking for a reason. I think we should close this issue for now, and if they change their minds later, we'll re-open it. Check out the [Essential subreddit](https://reddit.com/r/essential) for more community support.

**Comment by UrbanPotato** [comment]
I would't close this based on T1 support replies 
does no harm to keep it open for visibility

**Comment by Arunscape** [comment]
I vote the issue should not be closed solely based on this

also, it makes sense to keep it open for visibility

**Comment by 836554124** [comment]
希望官方能公布9008引导文件，很多手机就因为没有9008的引导文件导致黑砖，且无法救回

**Comment by TotalChris** [comment]
@836554124 I don't know if the Essential phone file is msm9008. I thought it was msm8998?

**Comment by 836554124** [comment]
yes,it's msm8998

**Comment by Nick80835** [comment]
> @836554124 I don't know if the Essential phone file is msm9008. I thought it was msm8998?

msm8998 is the chipset, 9008 is a sort of boot mode for EDL used among most modern qcom platforms

**Comment by jb-essential** [comment]
Can't be provided

**Comment by TotalChris** [comment]
@jb-essential could you provide us with a more verbose reason for this? We're all very confused.

**Comment by UrbanPotato** [comment]
if I had to guess its there signing key/vendor key from qualcom

**Comment by D1ll4nT** [comment]
Anyone who wants the signed firehose programmers and firmware files to unbrick your phone, please PM me. I finally got one of their employees to give up the goodies.

**Comment by TotalChris** [comment]
@dthrasherokc how does one PM on GitHub?

**Comment by Vigasaurus** [comment]
@dthrasherokc Github doesn't have a DM feature - if you could post a Discord/Reddit/Twitter username that'd be great :)

**Comment by itz63c** [comment]
> Anyone who wants the signed firehose programmers and firmware files to unbrick your phone, please PM me. I finally got one of their employees to give up the goodies.

GitHub does not have PM's
lol

**Comment by Darkhand81** [comment]
> Anyone who wants the signed firehose programmers and firmware files to unbrick your phone, please PM me. I finally got one of their employees to give up the goodies.

@dthrasherokc If you have it, I'd love a copy emailed to darkhand at gmail.  Thank you!

**Comment by Arunscape** [comment]
@dthrasherokc I'd love a copy as well arunscape@gmail.com

**Comment by I235078** [comment]
> 任何想要签名的firehose编程器和固件文件解开电话的人，请PM我。我终于让他们的一名雇员放弃了好东西。

renwuhe@gmail.com

**Comment by 836554124** [comment]
Excuse me, what is PM and DM

**Comment by TotalChris** [comment]
@836554124 https://www.youtube.com/watch?v=YXSpXO4N-tI

**Comment by 836554124** [comment]
@TotalChris Thank you

**Comment by Luorunze** [comment]
@TotalChris That is a music video .But what is PM and DM,thank you

**Comment by itz63c** [comment]
@Luorunze https://youtu.be/dQw4w9WgXcQ

**Comment by Luorunze** [comment]
@itz63c Are you seriously?

**Comment by itz63c** [comment]
@Luorunze Pussy Master and Dick Master

**Comment by TotalChris** [comment]
@itz63c Ah, I see you are a man of culture as well

**Comment by dthrasherokc** [comment]
hey guys sorry! My Twitter is dmthrasher. hit me up for the link!

**Comment by itz63c** [comment]
> hey guys sorry! My Twitter is dmthrasher. hit me up for the link!

you don't have your Twitter open for everyone to dm you or something, cause i can't start a dm. @itz63c on twitter

**Comment by TotalChris** [comment]
@dthrasherokc are these the same files we had before, or are they new ones? The Essential subreddit has been telling me that the userdebug.zip file is a firehose for development models, and doesn't work with their EDL PH-1s

**Comment by TotalChris** [comment]
Nvm, the latest version of the file I see is the same. Check the megathread on the subreddit reddit.com/r/essential. Someone diffed the certs and figured out they won't work.

**Comment by ommiao** [comment]
My PH1 is black brick now.

**Comment by teekey96** [comment]
My ph-1 is also bricked, i'm looking for someone who can help me.

**Comment by moradj** [comment]
Hi all is there a solution for the phone?
I have been waiting for the file since 2017
Unfortunately, there is no news from the developers

**Comment by modaozhiren** [comment]
@dthrasherokc 我的Essential Phone PH-1也砖了，能发我一份吗？十分感谢！这是我的邮箱1456254579@qq.com

**Comment by 123Yie** [comment]
Can I ask for a copy of the information? lye1152003@gmail.com Thank you very much.
