### ISSUE TITLE
HATO pretty please

### ISSUE THREAD

**Issue by kervurn** [EssentialOpenSource/device_essential_mata#3]
🙏 

(edit: or just ambientos framework i guess since we won't have devices)

**Comment by TotalChris** [comment]
[noob question] What exactly does HATO stand for?

**Comment by kervurn** [comment]
> [noob question] What exactly does HATO stand for?

codename for Home (which was killed in 2018). not an acronym afaik
e.g. MATA = PH-1, HATO = Home, etc.

**Comment by TotalChris** [comment]
This would actually be a great thing too. I saw the Dock prototype go up on ebay a while ago, so what if Essential became the first fully open-source company? (As in we have everything we need to build, maintain, and continue all of their projects even though they have stopped)

**Comment by jb-essential** [comment]
Not a part of this project
