### ISSUE TITLE
fastboot documentation/source

### ISSUE THREAD

**Issue by UrbanPotato** [EssentialOpenSource/device_essential_mata#4]
can we get some source or documentation on essentials fastboot implementation
the device doesn't have fastboot boot <image>.img or support for fastbootd enabled 

which makes testing kernel and recovery images a bit dodgy if you are doing something outside norms

**Comment by KurioHonoo** [comment]
Did you mean `fastboot boot <image>.img`?

**Comment by UrbanPotato** [comment]
yes without that testing kernels or recovery images could lead to hard bricking which we have no way 
to recovery from without firehouse/edl images/tool

**Comment by jb-essential** [comment]
Flashing boot/system/vendor will not brick a device (as ABL is untouched).

Unfortunately cannot provide more documentation
