### ISSUE TITLE
ETA for vendor.img? 

### ISSUE THREAD

**Issue by ripskee** [EssentialOpenSource/device_essential_mata#5]
When will the vendor.img be available?

**Comment by jb-essential** [comment]
Shorty - Just need final internal review and validation on the latest GSI for Android 11 to allow the community to use it

**Comment by jb-essential** [comment]
The image is available here

https://www.essential.com/developer/current-builds

**Comment by skatcat743** [comment]
Sorry to necro but the Essential website doesn't seem to be loading is there anywhere else that will have that vendor.img?

**Comment by OneNormalUsername** [comment]
@skatcat743 the direct download link (still up as of writing) is https://storage.googleapis.com/essential-static/vendor-QQ1A.200105.088.zip according to that [Reddit post](https://www.reddit.com/r/essential/comments/h0ipfa/android_11_beta_gsi_report/)

There is also an archive of the file on the [Wayback Machine](https://web.archive.org/web/20200301024838/https://storage.googleapis.com/essential-static/vendor-QQ1A.200105.088.zip)
