### ISSUE TITLE
Fix for QtiTelephonyService signature mismatch

### ISSUE THREAD

**Issue by anayw2001** [EssentialOpenSource/device_essential_mata#7]
If you can build device overlays via RRO to vendor, these 3 commits should fix QtiTelephonyService, enabling in-call audio on GSIs (in theory). Tested on StatiXOS, vendor overlay builds using the stock QQ1A February 2020 vendor.

https://review.statixos.com/c/android_frameworks_base/+/1695
https://review.statixos.com/c/android_frameworks_base/+/1696
https://review.statixos.com/c/android_device_essential_mata/+/1694

**Comment by jb-essential** [comment]
Thanks a lot.

The issue was fixed with a split APK and specifc SELinux domain.

https://github.com/EssentialOpenSource/device_essential_mata/commit/b8a287d83542b6e4113f36716bbc8a949ed363dd
