### ISSUE TITLE
FYI: Using older ccache may cause compile errors

### ISSUE THREAD

**Issue by pete4abw** [EssentialOpenSource/device_essential_mata#8]
When using CCACHE, it may throw errors in the compile process. I experienced this using ccache version **3.2.4**, According to the ccache maintainer, the bug was resolved in ccache version **3.7.6**. HTH

`ld.lld: error: undefined symbol ...`

from @jrosdahl:

> This turned out to be a interesting bug. It only manifests itself when using the opt-in sloppiness = file_macro mode, which the Android build apparently does by default. ...

See [This issue for complete discussion.](https://github.com/ccache/ccache/issues/489)

**Comment by jb-essential** [comment]
Thanks a lot for this FYI.
