### ISSUE TITLE
imsrcsd can't find symbols.

### ISSUE THREAD

**Issue by AKoskovich** [EssentialOpenSource/device_essential_mata#9]
05-14 12:53:15.744  2946  2946 F linker  : CANNOT LINK EXECUTABLE "/vendor/bin/imsrcsd": cannot locate symbol "_ZN7android4base10LogMessageC1EPKcjNS0_5LogIdENS0_11LogSeverityEi" referenced by "/vendor/bin/imsrcsd"...

This is on master BTW, but from what I understand it happens even on 10 still.

**Comment by jb-essential** [comment]
Need to add this function to the AOSP

android::base::LogMessage::LogMessage(char const*, unsigned int, android::base::LogId, android::base::LogSeverity, int)

So the version without TAG.

Can be added in base/include/android-base/logging.h

This will fix the issue (As imsrcsd is a prebuilt)
